// <auto-generated />
using System;
using BikeHaus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeHaus.Infrastructure.Migrations
{
    [DbContext(typeof(BikeHausDbContext))]
    [Migration("20260217201329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BikeHaus.Domain.Entities.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Farbe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rahmennummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reifengroesse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Rahmennummer");

                    b.ToTable("Bicycles");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ausweisnummer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hausnummer")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PLZ")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BicycleId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SaleId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BelegNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Kaufdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notizen")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zahlungsart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BelegNummer")
                        .IsUnique();

                    b.HasIndex("BicycleId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BelegNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuyerSignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Garantie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GarantieBedingungen")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notizen")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellerSignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Verkaufsdatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zahlungsart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BelegNummer")
                        .IsUnique();

                    b.HasIndex("BicycleId")
                        .IsUnique();

                    b.HasIndex("BuyerId");

                    b.HasIndex("BuyerSignatureId")
                        .IsUnique();

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.HasIndex("SellerSignatureId")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignatureType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Document", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithMany("Documents")
                        .HasForeignKey("BicycleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Documents")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Sale", "Sale")
                        .WithMany("Documents")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bicycle");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithOne("Purchase")
                        .HasForeignKey("BikeHaus.Domain.Entities.Purchase", "BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Customer", "Seller")
                        .WithMany("Purchases")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bicycle");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Sale", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithOne("Sale")
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Customer", "Buyer")
                        .WithMany("Sales")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Signature", "BuyerSignature")
                        .WithOne()
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "BuyerSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Purchase", "Purchase")
                        .WithOne("Sale")
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "PurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Signature", "SellerSignature")
                        .WithOne()
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "SellerSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bicycle");

                    b.Navigation("Buyer");

                    b.Navigation("BuyerSignature");

                    b.Navigation("Purchase");

                    b.Navigation("SellerSignature");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Signature", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Purchase", "Purchase")
                        .WithOne("Signature")
                        .HasForeignKey("BikeHaus.Domain.Entities.Signature", "PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Bicycle", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Sale");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
