// <auto-generated />
using System;
using BikeHaus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeHaus.Infrastructure.Migrations
{
    [DbContext(typeof(BikeHausDbContext))]
    [Migration("20260218010920_AddAccessoryCatalog")]
    partial class AddAccessoryCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BikeHaus.Domain.Entities.AccessoryCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Standardpreis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessoryCatalog");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fahrradtyp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Farbe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rahmennummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reifengroesse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StokNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zustand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Rahmennummer");

                    b.ToTable("Bicycles");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hausnummer")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PLZ")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReturnId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BicycleId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ReturnId");

                    b.HasIndex("SaleId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BelegNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Kaufdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notizen")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VerkaufspreisVorschlag")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zahlungsart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BelegNummer")
                        .IsUnique();

                    b.HasIndex("BicycleId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BelegNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerSignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Erstattungsbetrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Grund")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrundDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notizen")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Rueckgabedatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopSignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zahlungsart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BelegNummer")
                        .IsUnique();

                    b.HasIndex("BicycleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerSignatureId")
                        .IsUnique();

                    b.HasIndex("SaleId");

                    b.HasIndex("ShopSignatureId")
                        .IsUnique();

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BelegNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BicycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuyerSignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Garantie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GarantieBedingungen")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notizen")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SellerSignatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Verkaufsdatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Zahlungsart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BelegNummer")
                        .IsUnique();

                    b.HasIndex("BicycleId")
                        .IsUnique();

                    b.HasIndex("BuyerId");

                    b.HasIndex("BuyerSignatureId")
                        .IsUnique();

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.HasIndex("SellerSignatureId")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.SaleAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Menge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleAccessories");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.ShopSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BIC")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bankname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hausnummer")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("InhaberNachname")
                        .HasColumnType("TEXT");

                    b.Property<string>("InhaberSignatureBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("InhaberSignatureFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InhaberVorname")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oeffnungszeiten")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PLZ")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Steuernummer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UstIdNr")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zusatzinfo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShopSettings");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignatureType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Document", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithMany("Documents")
                        .HasForeignKey("BicycleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Documents")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Return", null)
                        .WithMany("Documents")
                        .HasForeignKey("ReturnId");

                    b.HasOne("BikeHaus.Domain.Entities.Sale", "Sale")
                        .WithMany("Documents")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bicycle");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithOne("Purchase")
                        .HasForeignKey("BikeHaus.Domain.Entities.Purchase", "BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Customer", "Seller")
                        .WithMany("Purchases")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bicycle");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Return", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithMany()
                        .HasForeignKey("BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Customer", "Customer")
                        .WithMany("Returns")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Signature", "CustomerSignature")
                        .WithOne()
                        .HasForeignKey("BikeHaus.Domain.Entities.Return", "CustomerSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Signature", "ShopSignature")
                        .WithOne()
                        .HasForeignKey("BikeHaus.Domain.Entities.Return", "ShopSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bicycle");

                    b.Navigation("Customer");

                    b.Navigation("CustomerSignature");

                    b.Navigation("Sale");

                    b.Navigation("ShopSignature");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Sale", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Bicycle", "Bicycle")
                        .WithOne("Sale")
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "BicycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Customer", "Buyer")
                        .WithMany("Sales")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeHaus.Domain.Entities.Signature", "BuyerSignature")
                        .WithOne()
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "BuyerSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Purchase", "Purchase")
                        .WithOne("Sale")
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "PurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeHaus.Domain.Entities.Signature", "SellerSignature")
                        .WithOne()
                        .HasForeignKey("BikeHaus.Domain.Entities.Sale", "SellerSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bicycle");

                    b.Navigation("Buyer");

                    b.Navigation("BuyerSignature");

                    b.Navigation("Purchase");

                    b.Navigation("SellerSignature");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.SaleAccessory", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Sale", "Sale")
                        .WithMany("Accessories")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Signature", b =>
                {
                    b.HasOne("BikeHaus.Domain.Entities.Purchase", "Purchase")
                        .WithOne("Signature")
                        .HasForeignKey("BikeHaus.Domain.Entities.Signature", "PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Bicycle", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Returns");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Sale");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Return", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BikeHaus.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
