import { Language } from './translation.service';

export interface CityLandingTranslation {
  metaTitle: string;
  metaDescription: string;
  heroTitle: string;
  heroSub: string;
  introHeading: string;
  introText: string;
  whyHeading: string;
  whyItems: string[];
  offerHeading: string;
  offerItems: string[];
  ctaHeading: string;
  ctaText: string;
  directions: string;
}

export interface CityLanding {
  slug: string;
  cityName: string;
  distanceKm: number;
  driveMinutes: number;
  translations: Record<Language, CityLandingTranslation>;
}

export const CITY_LANDINGS: CityLanding[] = [
  {
    slug: 'fahrrad-emmendingen',
    cityName: 'Emmendingen',
    distanceKm: 16,
    driveMinutes: 20,
    translations: {
      de: {
        metaTitle: 'Fahrrad Emmendingen — Fahrräder kaufen bei Karaarslan Bike',
        metaDescription: 'Fahrrad kaufen in Emmendingen? Karaarslan Bike ist nur 16 km entfernt. Über 100 neue & gebrauchte Fahrräder, E-Bikes mit Garantie. Probefahrt ohne Termin.',
        heroTitle: 'Fahrrad kaufen in Emmendingen?',
        heroSub: 'Karaarslan Bike — Ihr Fahrradladen nur 16 km von Emmendingen entfernt.',
        introHeading: 'Fahrräder für Emmendingen bei Karaarslan Bike',
        introText: 'Sie suchen ein Fahrrad in Emmendingen? Karaarslan Bike in der [ADRES], [SEHIR], ist nur 20 Minuten mit dem Auto entfernt. Bei uns finden Sie über 100 neue und gebrauchte Fahrräder — Citybikes, Trekkingräder, Mountainbikes, E-Bikes und Kinderfahrräder. Jedes Gebrauchtrad ist technisch geprüft und wird mit 3 Monaten Garantie verkauft.',
        whyHeading: 'Warum Karaarslan Bike für Emmendinger?',
        whyItems: [
          'Nur 16 km / 20 Minuten über die B3 oder L187',
          'Über 100 Fahrräder vorrätig — keine Wartezeit, keine Bestellung',
          'Geprüfte Gebrauchträder mit 3 Monaten Garantie',
          'Neue Fahrräder mit 24 Monaten Garantie',
          'Probefahrt vor Ort — ohne Termin',
          'Faire Preise — deutlich günstiger als viele Emmendinger Händler',
          'Beratung auf Deutsch, Englisch, Französisch und Türkisch',
        ],
        offerHeading: 'Unser Angebot',
        offerItems: [
          'Citybikes ab ca. 80 € (gebraucht) / ab 350 € (neu)',
          'Trekkingräder für Pendler und Freizeit',
          'E-Bikes ab ca. 800 € (gebraucht) — Akku-Zustand dokumentiert',
          'Mountainbikes für Trails im Schwarzwald',
          'Kinderfahrräder in allen Größen',
          'Fahrradzubehör: Schlösser, Helme, Beleuchtung, Körbe',
        ],
        ctaHeading: 'Jetzt vorbeikommen!',
        ctaText: 'Besuchen Sie uns in der [ADRES], [PLZ] [SEHIR]. Geöffnet Mo/Di/Do 11–18 Uhr, Fr 11–13 + 15–18 Uhr, Sa 11:30–17 Uhr. Oder schreiben Sie uns auf WhatsApp: [TELEFON].',
        directions: 'Folgen Sie der Navigation zu An der Wethmarheide 45, 44534 Lünen (Garagennummer 255). Kostenlose Parkplätze vorhanden.',
      },
      en: {
        metaTitle: 'Bicycle Emmendingen — Buy bikes at Karaarslan Bike',
        metaDescription: 'Buy a bike in Emmendingen? Karaarslan Bike is only 16 km away. Over 100 new & used bicycles, e-bikes with warranty. Test ride without appointment.',
        heroTitle: 'Buy a bicycle in Emmendingen?',
        heroSub: 'Karaarslan Bike — your bike shop only 16 km from Emmendingen.',
        introHeading: 'Bicycles for Emmendingen at Karaarslan Bike',
        introText: 'Looking for a bike in Emmendingen? Karaarslan Bike at [ADRES], [SEHIR], is only a 20-minute drive away. We have over 100 new and used bicycles — city bikes, trekking bikes, mountain bikes, e-bikes and children\'s bikes. Every used bike is technically inspected and comes with a 3-month warranty.',
        whyHeading: 'Why Karaarslan Bike for Emmendingen residents?',
        whyItems: [
          'Only 16 km / 20 minutes via the B3 or L187',
          'Over 100 bikes in stock — no waiting, no ordering',
          'Inspected used bikes with 3-month warranty',
          'New bicycles with 24-month warranty',
          'Test ride on site — no appointment needed',
          'Fair prices — significantly cheaper than many Emmendingen dealers',
          'Advice in German, English, French and Turkish',
        ],
        offerHeading: 'Our Range',
        offerItems: [
          'City bikes from approx. €80 (used) / from €350 (new)',
          'Trekking bikes for commuters and leisure',
          'E-bikes from approx. €800 (used) — battery condition documented',
          'Mountain bikes for Black Forest trails',
          'Children\'s bikes in all sizes',
          'Bike accessories: locks, helmets, lights, baskets',
        ],
        ctaHeading: 'Visit us now!',
        ctaText: 'Visit us at [ADRES], [PLZ] [SEHIR]. Open Mon/Tue/Thu 11–18, Fri 11–13 + 15–18, Sat 11:30–17. Or message us on WhatsApp: [TELEFON].',
        directions: 'Follow navigation to An der Wethmarheide 45, 44534 Lünen (Garagennummer 255). Free parking available.',
      },
      fr: {
        metaTitle: 'Vélo Emmendingen — Acheter des vélos chez Karaarslan Bike',
        metaDescription: 'Acheter un vélo à Emmendingen? Karaarslan Bike n\'est qu\'à 16 km. Plus de 100 vélos neufs et d\'occasion, vélos électriques avec garantie.',
        heroTitle: 'Acheter un vélo à Emmendingen?',
        heroSub: 'Karaarslan Bike — votre magasin de vélos à seulement 16 km d\'Emmendingen.',
        introHeading: 'Vélos pour Emmendingen chez Karaarslan Bike',
        introText: 'Vous cherchez un vélo à Emmendingen? Karaarslan Bike, [ADRES], [SEHIR], n\'est qu\'à 20 minutes en voiture. Nous proposons plus de 100 vélos neufs et d\'occasion — vélos de ville, VTC, VTT, vélos électriques et vélos pour enfants. Chaque vélo d\'occasion est contrôlé techniquement et vendu avec 3 mois de garantie.',
        whyHeading: 'Pourquoi Karaarslan Bike pour les habitants d\'Emmendingen?',
        whyItems: [
          'Seulement 16 km / 20 minutes via la B3 ou L187',
          'Plus de 100 vélos en stock — sans attente',
          'Vélos d\'occasion contrôlés avec 3 mois de garantie',
          'Vélos neufs avec 24 mois de garantie',
          'Essai sur place — sans rendez-vous',
          'Prix justes — nettement moins cher que beaucoup de revendeurs d\'Emmendingen',
          'Conseils en allemand, anglais, français et turc',
        ],
        offerHeading: 'Notre offre',
        offerItems: [
          'Vélos de ville à partir d\'env. 80 € (occasion) / 350 € (neuf)',
          'VTC pour les trajets et les loisirs',
          'Vélos électriques à partir d\'env. 800 € (occasion) — état de la batterie documenté',
          'VTT pour les sentiers de la Forêt-Noire',
          'Vélos pour enfants dans toutes les tailles',
          'Accessoires vélo: antivols, casques, éclairage, paniers',
        ],
        ctaHeading: 'Venez nous voir!',
        ctaText: 'Rendez-nous visite au [ADRES], [PLZ] [SEHIR]. Ouvert lun/mar/jeu 11h–18h, ven 11h–13h + 15h–18h, sam 11h30–17h. Ou écrivez-nous sur WhatsApp: [TELEFON].',
        directions: 'Suivez la navigation jusqu\'à An der Wethmarheide 45, 44534 Lünen (Garagennummer 255). Parking gratuit disponible.',
      },
      tr: {
        metaTitle: 'Bisiklet Emmendingen — Karaarslan Bike\'da bisiklet alın',
        metaDescription: 'Emmendingen\'de bisiklet mi arıyorsunuz? Karaarslan Bike sadece 16 km uzaklıkta. 100\'den fazla yeni ve ikinci el bisiklet, e-bisiklet, garantili.',
        heroTitle: 'Emmendingen\'de bisiklet mi arıyorsunuz?',
        heroSub: 'Karaarslan Bike — Emmendingen\'den sadece 16 km uzaklıkta bisiklet mağazanız.',
        introHeading: 'Emmendingen için bisikletler — Karaarslan Bike',
        introText: 'Emmendingen\'de bisiklet mi arıyorsunuz? Karaarslan Bike, [ADRES], [SEHIR], arabayla sadece 20 dakika uzaklıkta. 100\'den fazla yeni ve ikinci el bisiklet — şehir bisikletleri, trekking bisikletleri, dağ bisikletleri, e-bisikletler ve çocuk bisikletleri. Her ikinci el bisiklet teknik olarak kontrol edilmiş ve 3 ay garantili.',
        whyHeading: 'Emmendingen\'liler neden Bike Haus\'u tercih etmeli?',
        whyItems: [
          'Sadece 16 km / 20 dakika B3 veya L187 üzerinden',
          'Stokta 100\'den fazla bisiklet — bekleme yok',
          'Kontrol edilmiş ikinci el bisikletler, 3 ay garantili',
          'Yeni bisikletler 24 ay garantili',
          'Yerinde test sürüşü — randevusuz',
          'Uygun fiyatlar — birçok Emmendingen satıcısından çok daha ucuz',
          'Almanca, İngilizce, Fransızca ve Türkçe danışmanlık',
        ],
        offerHeading: 'Ürün Yelpazemiz',
        offerItems: [
          'Şehir bisikletleri yaklaşık 80 €\'dan (ikinci el) / 350 €\'dan (yeni)',
          'İşe gidip gelme ve boş zaman için trekking bisikletleri',
          'E-bisikletler yaklaşık 800 €\'dan (ikinci el) — akü durumu belgelenmiş',
          'Schwarzwald parkurları için dağ bisikletleri',
          'Tüm bedenlerde çocuk bisikletleri',
          'Bisiklet aksesuarları: kilitler, kasklar, aydınlatma, sepetler',
        ],
        ctaHeading: 'Hemen gelin!',
        ctaText: '[ADRES], [PLZ] [SEHIR] adresine gelin. Açılış saatleri: Pzt/Sal/Per 11–18, Cum 11–13 + 15–18, Cmt 11:30–17. Ya da WhatsApp\'tan yazın: [TELEFON].',
        directions: 'Navigasyonu An der Wethmarheide 45, 44534 Lünen (Garagennummer 255) adresine ayarlayın. Ücretsiz park yeri mevcut.',
      },
    },
  },
  {
    slug: 'fahrrad-bad-krozingen',
    cityName: 'Bad Krozingen',
    distanceKm: 18,
    driveMinutes: 22,
    translations: {
      de: {
        metaTitle: 'Fahrrad Bad Krozingen — Fahrräder kaufen bei Karaarslan Bike',
        metaDescription: 'Fahrrad kaufen in Bad Krozingen? Karaarslan Bike: Nur 18 km entfernt. 100+ neue & gebrauchte Fahrräder, E-Bikes, Garantie, Probefahrt.',
        heroTitle: 'Fahrrad kaufen in Bad Krozingen?',
        heroSub: 'Karaarslan Bike — nur 18 km von Bad Krozingen. Über 100 Fahrräder mit Garantie.',
        introHeading: 'Fahrräder für Bad Krozingen bei Karaarslan Bike',
        introText: 'Bad Krozingen und Umgebung suchen ein gutes Fahrrad? Karaarslan Bike bietet Ihnen über 100 neue und gebrauchte Fahrräder — nur 22 Minuten Fahrt über die B3. Ob Citybike für den Alltag, E-Bike für die Hügel im Markgräflerland oder Trekkingrad für längere Touren — wir haben das passende Rad.',
        whyHeading: 'Warum von Bad Krozingen zu uns kommen?',
        whyItems: [
          'Nur 18 km / 22 Minuten über die B3',
          'Über 100 Fahrräder sofort verfügbar',
          'Geprüfte Gebrauchträder mit 3 Monaten Garantie',
          'E-Bikes mit dokumentiertem Akku-Zustand',
          'Kostenlose Probefahrt — ohne Termin',
          'Faire, transparente Preise',
        ],
        offerHeading: 'Unser Angebot',
        offerItems: [
          'Citybikes und Hollandräder für den Alltag',
          'E-Bikes für die Hügel im Markgräflerland',
          'Trekkingräder für den Dreisamtal-Radweg',
          'Kinderfahrräder in allen Größen',
          'Gebrauchte Fahrräder ab ca. 80 €',
        ],
        ctaHeading: 'Besuchen Sie uns!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Mo/Di/Do 11–18 Uhr, Fr 11–13 + 15–18 Uhr, Sa 11:30–17 Uhr. WhatsApp: [TELEFON].',
        directions: 'Von Bad Krozingen über die B3 Richtung [SEHIR]-Süd. Dauer: ca. 22 Minuten. Kostenlose Parkplätze vor dem Geschäft.',
      },
      en: {
        metaTitle: 'Bicycle Bad Krozingen — Buy bikes at Karaarslan Bike',
        metaDescription: 'Buy a bike in Bad Krozingen? Karaarslan Bike: Only 18 km away. 100+ new & used bicycles, e-bikes, warranty, test rides.',
        heroTitle: 'Buy a bicycle in Bad Krozingen?',
        heroSub: 'Karaarslan Bike — only 18 km from Bad Krozingen. Over 100 bikes with warranty.',
        introHeading: 'Bicycles for Bad Krozingen at Karaarslan Bike',
        introText: 'Looking for a good bike in Bad Krozingen and the surrounding area? Karaarslan Bike offers over 100 new and used bicycles — just a 22-minute drive via the B3. Whether a city bike for everyday use, an e-bike for the Markgräflerland hills, or a trekking bike for longer tours — we have the right bike for you.',
        whyHeading: 'Why come from Bad Krozingen to us?',
        whyItems: [
          'Only 18 km / 22 minutes via the B3',
          'Over 100 bikes immediately available',
          'Inspected used bikes with 3-month warranty',
          'E-bikes with documented battery condition',
          'Free test ride — no appointment needed',
          'Fair, transparent prices',
        ],
        offerHeading: 'Our Range',
        offerItems: [
          'City bikes and Dutch bikes for everyday use',
          'E-bikes for the Markgräflerland hills',
          'Trekking bikes for the Dreisamtal cycle path',
          'Children\'s bikes in all sizes',
          'Used bicycles from approx. €80',
        ],
        ctaHeading: 'Visit us!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Open Mon/Tue/Thu 11–18, Fri 11–13 + 15–18, Sat 11:30–17. WhatsApp: [TELEFON].',
        directions: 'From Bad Krozingen via the B3 towards [SEHIR]-Süd. Duration: approx. 22 minutes. Free parking in front of the shop.',
      },
      fr: {
        metaTitle: 'Vélo Bad Krozingen — Acheter des vélos chez Karaarslan Bike',
        metaDescription: 'Acheter un vélo à Bad Krozingen? Karaarslan Bike: seulement 18 km. 100+ vélos neufs et d\'occasion, vélos électriques, garantie.',
        heroTitle: 'Acheter un vélo à Bad Krozingen?',
        heroSub: 'Karaarslan Bike — à seulement 18 km de Bad Krozingen. Plus de 100 vélos avec garantie.',
        introHeading: 'Vélos pour Bad Krozingen chez Karaarslan Bike',
        introText: 'Vous cherchez un bon vélo à Bad Krozingen et ses environs? Karaarslan Bike vous propose plus de 100 vélos neufs et d\'occasion — à seulement 22 minutes en voiture via la B3. Vélo de ville, vélo électrique pour les collines du Markgräflerland ou VTC pour les longues randonnées — nous avons le vélo qu\'il vous faut.',
        whyHeading: 'Pourquoi venir de Bad Krozingen chez nous?',
        whyItems: [
          'Seulement 18 km / 22 minutes via la B3',
          'Plus de 100 vélos immédiatement disponibles',
          'Vélos d\'occasion contrôlés avec 3 mois de garantie',
          'Vélos électriques avec état de batterie documenté',
          'Essai gratuit — sans rendez-vous',
          'Prix justes et transparents',
        ],
        offerHeading: 'Notre offre',
        offerItems: [
          'Vélos de ville et hollandais pour le quotidien',
          'Vélos électriques pour les collines du Markgräflerland',
          'VTC pour la piste cyclable du Dreisamtal',
          'Vélos pour enfants dans toutes les tailles',
          'Vélos d\'occasion à partir d\'env. 80 €',
        ],
        ctaHeading: 'Venez nous voir!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Ouvert lun/mar/jeu 11h–18h, ven 11h–13h + 15h–18h, sam 11h30–17h. WhatsApp: [TELEFON].',
        directions: 'Depuis Bad Krozingen via la B3 direction [SEHIR]-Süd. Durée: env. 22 minutes. Parking gratuit devant le magasin.',
      },
      tr: {
        metaTitle: 'Bisiklet Bad Krozingen — Karaarslan Bike\'da bisiklet alın',
        metaDescription: 'Bad Krozingen\'de bisiklet mi arıyorsunuz? Karaarslan Bike sadece 18 km uzaklıkta. 100+ yeni ve ikinci el bisiklet, garantili.',
        heroTitle: 'Bad Krozingen\'de bisiklet mi arıyorsunuz?',
        heroSub: 'Karaarslan Bike — Bad Krozingen\'den sadece 18 km. 100\'den fazla garantili bisiklet.',
        introHeading: 'Bad Krozingen için bisikletler — Karaarslan Bike',
        introText: 'Bad Krozingen ve çevresinde iyi bir bisiklet mi arıyorsunuz? Karaarslan Bike, B3 üzerinden sadece 22 dakika uzaklıkta, 100\'den fazla yeni ve ikinci el bisiklet sunuyor. Günlük kullanım için şehir bisikleti, Markgräflerland tepeleri için e-bisiklet veya uzun turlar için trekking bisikleti — sizin için doğru bisiklete sahibiz.',
        whyHeading: 'Bad Krozingen\'den neden bize gelmeli?',
        whyItems: [
          'Sadece 18 km / 22 dakika B3 üzerinden',
          'Stokta 100\'den fazla bisiklet',
          'Kontrol edilmiş ikinci el bisikletler, 3 ay garantili',
          'Akü durumu belgelenmiş e-bisikletler',
          'Ücretsiz test sürüşü — randevusuz',
          'Adil, şeffaf fiyatlar',
        ],
        offerHeading: 'Ürün Yelpazemiz',
        offerItems: [
          'Günlük kullanım için şehir ve Hollanda bisikletleri',
          'Markgräflerland tepeleri için e-bisikletler',
          'Dreisamtal bisiklet yolu için trekking bisikletleri',
          'Tüm bedenlerde çocuk bisikletleri',
          'İkinci el bisikletler yaklaşık 80 €\'dan',
        ],
        ctaHeading: 'Bizi ziyaret edin!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Pzt/Sal/Per 11–18, Cum 11–13 + 15–18, Cmt 11:30–17. WhatsApp: [TELEFON].',
        directions: 'Bad Krozingen\'den B3 üzerinden [SEHIR]-Süd yönüne. Süre: yaklaşık 22 dakika. Mağaza önünde ücretsiz park yeri.',
      },
    },
  },
  {
    slug: 'fahrrad-breisach',
    cityName: 'Breisach am Rhein',
    distanceKm: 25,
    driveMinutes: 28,
    translations: {
      de: {
        metaTitle: 'Fahrrad Breisach — Fahrräder kaufen bei Karaarslan Bike',
        metaDescription: 'Fahrrad kaufen in Breisach? Karaarslan Bike: 25 km entfernt, 100+ Fahrräder, E-Bikes, Garantie, Probefahrt ohne Termin.',
        heroTitle: 'Fahrrad kaufen in Breisach?',
        heroSub: 'Karaarslan Bike — die große Auswahl nur 25 km von Breisach entfernt.',
        introHeading: 'Fahrräder für Breisach bei Karaarslan Bike',
        introText: 'In Breisach am Rhein und Umgebung gibt es wenige spezialisierte Fahrradhändler. Karaarslan Bike bietet Ihnen die Auswahl, die Sie verdienen: über 100 neue und gebrauchte Fahrräder mit Garantie, nur 28 Minuten entfernt.',
        whyHeading: 'Warum die kurze Fahrt lohnt',
        whyItems: [
          'Nur 25 km / 28 Minuten über die B31',
          'Größte Auswahl in der Region — über 100 Fahrräder',
          'Gebrauchträder mit Garantie',
          'E-Bikes mit geprüftem Akku',
          'Probefahrt ohne Termin',
          'Parkplätze direkt vor dem Geschäft',
        ],
        offerHeading: 'Das erwartet Sie',
        offerItems: [
          'Citybikes für den Alltag in Breisach und Umgebung',
          'Trekkingräder für den Rhein-Radweg',
          'E-Bikes für die Fahrten zwischen Breisach und [SEHIR]',
          'Mountainbikes für den Kaiserstuhl',
          'Kinderfahrräder für den Schulweg',
        ],
        ctaHeading: 'Kommen Sie vorbei!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Mo/Di/Do 11–18 Uhr, Fr 11–13 + 15–18 Uhr, Sa 11:30–17 Uhr. WhatsApp: [TELEFON].',
        directions: 'Von Breisach über die B31 Richtung [SEHIR]. In ca. 28 Minuten bei uns. Parkplätze vorhanden.',
      },
      en: {
        metaTitle: 'Bicycle Breisach — Buy bikes at Karaarslan Bike',
        metaDescription: 'Buy a bike in Breisach? Karaarslan Bike: 25 km away, 100+ bicycles, e-bikes, warranty, test ride without appointment.',
        heroTitle: 'Buy a bicycle in Breisach?',
        heroSub: 'Karaarslan Bike — the big selection only 25 km from Breisach.',
        introHeading: 'Bicycles for Breisach at Karaarslan Bike',
        introText: 'There are few specialized bicycle dealers in Breisach am Rhein and the surrounding area. Karaarslan Bike offers you the selection you deserve: over 100 new and used bicycles with warranty, only 28 minutes away.',
        whyHeading: 'Why the short drive is worth it',
        whyItems: [
          'Only 25 km / 28 minutes via the B31',
          'Largest selection in the region — over 100 bicycles',
          'Used bikes with warranty',
          'E-bikes with inspected battery',
          'Test ride without appointment',
          'Parking directly in front of the shop',
        ],
        offerHeading: 'What awaits you',
        offerItems: [
          'City bikes for everyday use in Breisach and surroundings',
          'Trekking bikes for the Rhine cycle path',
          'E-bikes for trips between Breisach and [SEHIR]',
          'Mountain bikes for the Kaiserstuhl',
          'Children\'s bikes for the school commute',
        ],
        ctaHeading: 'Come visit us!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Open Mon/Tue/Thu 11–18, Fri 11–13 + 15–18, Sat 11:30–17. WhatsApp: [TELEFON].',
        directions: 'From Breisach via the B31 towards [SEHIR]. About 28 minutes to reach us. Parking available.',
      },
      fr: {
        metaTitle: 'Vélo Breisach — Acheter des vélos chez Karaarslan Bike',
        metaDescription: 'Acheter un vélo à Breisach? Karaarslan Bike: 25 km, 100+ vélos, vélos électriques, garantie, essai sans rendez-vous.',
        heroTitle: 'Acheter un vélo à Breisach?',
        heroSub: 'Karaarslan Bike — le grand choix à seulement 25 km de Breisach.',
        introHeading: 'Vélos pour Breisach chez Karaarslan Bike',
        introText: 'Il y a peu de marchands de vélos spécialisés à Breisach am Rhein et ses environs. Karaarslan Bike vous offre le choix que vous méritez: plus de 100 vélos neufs et d\'occasion avec garantie, à seulement 28 minutes.',
        whyHeading: 'Pourquoi le court trajet en vaut la peine',
        whyItems: [
          'Seulement 25 km / 28 minutes via la B31',
          'Plus grand choix de la région — plus de 100 vélos',
          'Vélos d\'occasion avec garantie',
          'Vélos électriques avec batterie contrôlée',
          'Essai sans rendez-vous',
          'Parking directement devant le magasin',
        ],
        offerHeading: 'Ce qui vous attend',
        offerItems: [
          'Vélos de ville pour le quotidien à Breisach et environs',
          'VTC pour la piste cyclable du Rhin',
          'Vélos électriques pour les trajets entre Breisach et [SEHIR]',
          'VTT pour le Kaiserstuhl',
          'Vélos pour enfants pour le trajet scolaire',
        ],
        ctaHeading: 'Venez nous voir!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Ouvert lun/mar/jeu 11h–18h, ven 11h–13h + 15h–18h, sam 11h30–17h. WhatsApp: [TELEFON].',
        directions: 'Depuis Breisach via la B31 direction [SEHIR]. En env. 28 minutes chez nous. Parking disponible.',
      },
      tr: {
        metaTitle: 'Bisiklet Breisach — Karaarslan Bike\'da bisiklet alın',
        metaDescription: 'Breisach\'da bisiklet mi arıyorsunuz? Karaarslan Bike: 25 km uzaklıkta, 100+ bisiklet, garantili, randevusuz test sürüşü.',
        heroTitle: 'Breisach\'da bisiklet mi arıyorsunuz?',
        heroSub: 'Karaarslan Bike — Breisach\'dan sadece 25 km uzaklıkta geniş seçenek.',
        introHeading: 'Breisach için bisikletler — Karaarslan Bike',
        introText: 'Breisach am Rhein ve çevresinde uzmanlaşmış bisiklet satıcıları çok az. Karaarslan Bike size hak ettiğiniz seçeneği sunuyor: garantili 100\'den fazla yeni ve ikinci el bisiklet, sadece 28 dakika uzaklıkta.',
        whyHeading: 'Kısa yolculuk neden buna değer',
        whyItems: [
          'Sadece 25 km / 28 dakika B31 üzerinden',
          'Bölgenin en büyük seçimi — 100\'den fazla bisiklet',
          'Garantili ikinci el bisikletler',
          'Kontrol edilmiş akülü e-bisikletler',
          'Randevusuz test sürüşü',
          'Mağaza önünde park yeri',
        ],
        offerHeading: 'Sizi neler bekliyor',
        offerItems: [
          'Breisach ve çevresinde günlük kullanım için şehir bisikletleri',
          'Ren bisiklet yolu için trekking bisikletleri',
          'Breisach-[SEHIR] arası yolculuklar için e-bisikletler',
          'Kaiserstuhl için dağ bisikletleri',
          'Okul yolu için çocuk bisikletleri',
        ],
        ctaHeading: 'Bize uğrayın!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Pzt/Sal/Per 11–18, Cum 11–13 + 15–18, Cmt 11:30–17. WhatsApp: [TELEFON].',
        directions: 'Breisach\'dan B31 üzerinden [SEHIR] yönüne. Yaklaşık 28 dakikada bizde. Park yeri mevcut.',
      },
    },
  },
  {
    slug: 'fahrrad-gundelfingen',
    cityName: 'Gundelfingen',
    distanceKm: 8,
    driveMinutes: 12,
    translations: {
      de: {
        metaTitle: 'Fahrrad Gundelfingen — Fahrräder kaufen bei Karaarslan Bike',
        metaDescription: 'Fahrrad kaufen in Gundelfingen? Karaarslan Bike: Nur 8 km entfernt! 100+ neue & gebrauchte Fahrräder, E-Bikes, Garantie.',
        heroTitle: 'Fahrrad kaufen in Gundelfingen?',
        heroSub: 'Karaarslan Bike — Ihr Nachbar-Fahrradladen, nur 8 km entfernt.',
        introHeading: 'Fahrräder für Gundelfingen bei Karaarslan Bike',
        introText: 'Gundelfingen liegt direkt nördlich von [SEHIR] — und Karaarslan Bike ist nur 12 Minuten mit dem Auto oder 25 Minuten mit dem Fahrrad entfernt. Perfekt für eine Probefahrt! Wir bieten über 100 neue und gebrauchte Fahrräder mit Garantie.',
        whyHeading: 'Warum Bike Haus für Gundelfinger?',
        whyItems: [
          'Nur 8 km / 12 Minuten mit dem Auto',
          'Auch mit dem Fahrrad (25 min) oder Straßenbahn erreichbar',
          'Über 100 Fahrräder zum Probefahren',
          'Gebrauchträder mit 3 Monaten Garantie',
          'Faire Preise',
        ],
        offerHeading: 'Unser Sortiment',
        offerItems: [
          'Citybikes für den Pendelweg nach [SEHIR]',
          'E-Bikes für entspanntes Pendeln',
          'Trekkingräder für Freizeittouren im Dreisamtal',
          'Kinderfahrräder für alle Altersgruppen',
          'Gebrauchte Fahrräder ab ca. 80 €',
        ],
        ctaHeading: 'Jetzt vorbeikommen!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Mo/Di/Do 11–18 Uhr, Fr 11–13 + 15–18 Uhr, Sa 11:30–17 Uhr. WhatsApp: [TELEFON].',
        directions: 'Von Gundelfingen über die Freiburger Landstraße Richtung [SEHIR]-Haslach. Nur 12 Minuten.',
      },
      en: {
        metaTitle: 'Bicycle Gundelfingen — Buy bikes at Karaarslan Bike',
        metaDescription: 'Buy a bike in Gundelfingen? Karaarslan Bike: Only 8 km away! 100+ new & used bicycles, e-bikes, warranty.',
        heroTitle: 'Buy a bicycle in Gundelfingen?',
        heroSub: 'Karaarslan Bike — your neighbourhood bike shop, only 8 km away.',
        introHeading: 'Bicycles for Gundelfingen at Karaarslan Bike',
        introText: 'Gundelfingen is located just north of [SEHIR] — and Karaarslan Bike is only a 12-minute drive or 25-minute bike ride away. Perfect for a test ride! We offer over 100 new and used bicycles with warranty.',
        whyHeading: 'Why Bike Haus for Gundelfingen residents?',
        whyItems: [
          'Only 8 km / 12 minutes by car',
          'Also reachable by bike (25 min) or tram',
          'Over 100 bikes to test ride',
          'Used bikes with 3-month warranty',
          'Fair prices',
        ],
        offerHeading: 'Our Selection',
        offerItems: [
          'City bikes for commuting to [SEHIR]',
          'E-bikes for relaxed commuting',
          'Trekking bikes for leisure tours in the Dreisamtal',
          'Children\'s bikes for all age groups',
          'Used bicycles from approx. €80',
        ],
        ctaHeading: 'Visit us now!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Open Mon/Tue/Thu 11–18, Fri 11–13 + 15–18, Sat 11:30–17. WhatsApp: [TELEFON].',
        directions: 'From Gundelfingen via Freiburger Landstraße towards [SEHIR]-Haslach. Only 12 minutes.',
      },
      fr: {
        metaTitle: 'Vélo Gundelfingen — Acheter des vélos chez Karaarslan Bike',
        metaDescription: 'Acheter un vélo à Gundelfingen? Karaarslan Bike: seulement 8 km! 100+ vélos neufs et d\'occasion, vélos électriques, garantie.',
        heroTitle: 'Acheter un vélo à Gundelfingen?',
        heroSub: 'Karaarslan Bike — votre magasin de vélos voisin, à seulement 8 km.',
        introHeading: 'Vélos pour Gundelfingen chez Karaarslan Bike',
        introText: 'Gundelfingen est situé juste au nord de [SEHIR] — et Karaarslan Bike n\'est qu\'à 12 minutes en voiture ou 25 minutes à vélo. Parfait pour un essai! Nous proposons plus de 100 vélos neufs et d\'occasion avec garantie.',
        whyHeading: 'Pourquoi Bike Haus pour les habitants de Gundelfingen?',
        whyItems: [
          'Seulement 8 km / 12 minutes en voiture',
          'Aussi accessible en vélo (25 min) ou en tramway',
          'Plus de 100 vélos à essayer',
          'Vélos d\'occasion avec 3 mois de garantie',
          'Prix justes',
        ],
        offerHeading: 'Notre sélection',
        offerItems: [
          'Vélos de ville pour les trajets vers [SEHIR]',
          'Vélos électriques pour un trajet détendu',
          'VTC pour les randonnées dans le Dreisamtal',
          'Vélos pour enfants pour tous les âges',
          'Vélos d\'occasion à partir d\'env. 80 €',
        ],
        ctaHeading: 'Venez nous voir!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Ouvert lun/mar/jeu 11h–18h, ven 11h–13h + 15h–18h, sam 11h30–17h. WhatsApp: [TELEFON].',
        directions: 'Depuis Gundelfingen via Freiburger Landstraße direction [SEHIR]-Haslach. Seulement 12 minutes.',
      },
      tr: {
        metaTitle: 'Bisiklet Gundelfingen — Karaarslan Bike\'da bisiklet alın',
        metaDescription: 'Gundelfingen\'de bisiklet mi arıyorsunuz? Karaarslan Bike sadece 8 km uzaklıkta! 100+ yeni ve ikinci el bisiklet, garantili.',
        heroTitle: 'Gundelfingen\'de bisiklet mi arıyorsunuz?',
        heroSub: 'Karaarslan Bike — komşu bisiklet mağazanız, sadece 8 km uzaklıkta.',
        introHeading: 'Gundelfingen için bisikletler — Karaarslan Bike',
        introText: 'Gundelfingen, [SEHIR]\'un hemen kuzeyinde yer alıyor — ve Karaarslan Bike arabayla sadece 12 dakika veya bisikletle 25 dakika uzaklıkta. Test sürüşü için mükemmel! Garantili 100\'den fazla yeni ve ikinci el bisiklet sunuyoruz.',
        whyHeading: 'Gundelfingen\'liler neden Bike Haus\'u tercih etmeli?',
        whyItems: [
          'Sadece 8 km / 12 dakika arabayla',
          'Bisikletle (25 dk) veya tramvayla da ulaşılabilir',
          'Test sürüşü yapılabilecek 100\'den fazla bisiklet',
          '3 ay garantili ikinci el bisikletler',
          'Uygun fiyatlar',
        ],
        offerHeading: 'Ürün Seçimimiz',
        offerItems: [
          '[SEHIR]\'a gidiş-geliş için şehir bisikletleri',
          'Rahat ulaşım için e-bisikletler',
          'Dreisamtal\'da boş zaman turları için trekking bisikletleri',
          'Tüm yaş grupları için çocuk bisikletleri',
          'İkinci el bisikletler yaklaşık 80 €\'dan',
        ],
        ctaHeading: 'Hemen gelin!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Pzt/Sal/Per 11–18, Cum 11–13 + 15–18, Cmt 11:30–17. WhatsApp: [TELEFON].',
        directions: 'Gundelfingen\'den Freiburger Landstraße üzerinden [SEHIR]-Haslach yönüne. Sadece 12 dakika.',
      },
    },
  },
  {
    slug: 'fahrrad-march',
    cityName: 'March',
    distanceKm: 10,
    driveMinutes: 15,
    translations: {
      de: {
        metaTitle: 'Fahrrad March — Fahrräder kaufen bei Karaarslan Bike',
        metaDescription: 'Fahrrad kaufen in March? Karaarslan Bike: 10 km entfernt, 100+ Fahrräder, E-Bikes, Garantie, Probefahrt.',
        heroTitle: 'Fahrrad kaufen in March?',
        heroSub: 'Karaarslan Bike — nur 10 km von March entfernt. Große Auswahl, faire Preise.',
        introHeading: 'Fahrräder für March bei Karaarslan Bike',
        introText: 'March (Hugstetten, Neuershausen, Holzhausen) liegt westlich von [SEHIR]. Karaarslan Bike ist in nur 15 Minuten erreichbar und bietet Ihnen die größte Fahrradauswahl der Region — über 100 neue und gebrauchte Fahrräder mit Garantie.',
        whyHeading: 'Warum zu uns kommen?',
        whyItems: [
          'Nur 10 km / 15 Minuten mit dem Auto',
          'Über 100 Fahrräder sofort verfügbar',
          'Geprüfte Gebrauchträder mit Garantie',
          'E-Bikes mit dokumentiertem Akku-Zustand',
          'Probefahrt ohne Termin',
        ],
        offerHeading: 'Unser Angebot',
        offerItems: [
          'Citybikes für den Alltag',
          'E-Bikes für die Strecke March – [SEHIR]',
          'Trekkingräder für Touren im Ruhrgebiet',
          'Kinderfahrräder',
          'Gebrauchte Fahrräder ab ca. 80 €',
        ],
        ctaHeading: 'Besuchen Sie uns!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Mo/Di/Do 11–18 Uhr, Fr 11–13 + 15–18 Uhr, Sa 11:30–17 Uhr. WhatsApp: [TELEFON].',
        directions: 'Von March über Hugstetten/Umkirch direkt nach [SEHIR]-Haslach. Nur 15 Minuten.',
      },
      en: {
        metaTitle: 'Bicycle March — Buy bikes at Karaarslan Bike',
        metaDescription: 'Buy a bike in March? Karaarslan Bike: 10 km away, 100+ bicycles, e-bikes, warranty, test rides.',
        heroTitle: 'Buy a bicycle in March?',
        heroSub: 'Karaarslan Bike — only 10 km from March. Large selection, fair prices.',
        introHeading: 'Bicycles for March at Karaarslan Bike',
        introText: 'March (Hugstetten, Neuershausen, Holzhausen) is located west of [SEHIR]. Karaarslan Bike is reachable in just 15 minutes and offers you the largest bicycle selection in the region — over 100 new and used bicycles with warranty.',
        whyHeading: 'Why come to us?',
        whyItems: [
          'Only 10 km / 15 minutes by car',
          'Over 100 bikes immediately available',
          'Inspected used bikes with warranty',
          'E-bikes with documented battery condition',
          'Test ride without appointment',
        ],
        offerHeading: 'Our Range',
        offerItems: [
          'City bikes for everyday use',
          'E-bikes for the March – [SEHIR] route',
          'Trekking bikes for tours in the Breisgau',
          'Children\'s bikes',
          'Used bicycles from approx. €80',
        ],
        ctaHeading: 'Visit us!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Open Mon/Tue/Thu 11–18, Fri 11–13 + 15–18, Sat 11:30–17. WhatsApp: [TELEFON].',
        directions: 'From March via Hugstetten/Umkirch directly to [SEHIR]-Haslach. Only 15 minutes.',
      },
      fr: {
        metaTitle: 'Vélo March — Acheter des vélos chez Karaarslan Bike',
        metaDescription: 'Acheter un vélo à March? Karaarslan Bike: 10 km, 100+ vélos, vélos électriques, garantie, essai.',
        heroTitle: 'Acheter un vélo à March?',
        heroSub: 'Karaarslan Bike — à seulement 10 km de March. Grand choix, prix justes.',
        introHeading: 'Vélos pour March chez Karaarslan Bike',
        introText: 'March (Hugstetten, Neuershausen, Holzhausen) est situé à l\'ouest de [SEHIR]. Karaarslan Bike est accessible en seulement 15 minutes et vous offre le plus grand choix de vélos de la région — plus de 100 vélos neufs et d\'occasion avec garantie.',
        whyHeading: 'Pourquoi venir chez nous?',
        whyItems: [
          'Seulement 10 km / 15 minutes en voiture',
          'Plus de 100 vélos immédiatement disponibles',
          'Vélos d\'occasion contrôlés avec garantie',
          'Vélos électriques avec état de batterie documenté',
          'Essai sans rendez-vous',
        ],
        offerHeading: 'Notre offre',
        offerItems: [
          'Vélos de ville pour le quotidien',
          'Vélos électriques pour le trajet March – [SEHIR]',
          'VTC pour les randonnées dans le Breisgau',
          'Vélos pour enfants',
          'Vélos d\'occasion à partir d\'env. 80 €',
        ],
        ctaHeading: 'Venez nous voir!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Ouvert lun/mar/jeu 11h–18h, ven 11h–13h + 15h–18h, sam 11h30–17h. WhatsApp: [TELEFON].',
        directions: 'Depuis March via Hugstetten/Umkirch directement vers [SEHIR]-Haslach. Seulement 15 minutes.',
      },
      tr: {
        metaTitle: 'Bisiklet March — Karaarslan Bike\'da bisiklet alın',
        metaDescription: 'March\'da bisiklet mi arıyorsunuz? Karaarslan Bike: 10 km uzaklıkta, 100+ bisiklet, garantili.',
        heroTitle: 'March\'da bisiklet mi arıyorsunuz?',
        heroSub: 'Karaarslan Bike — March\'dan sadece 10 km. Geniş seçenek, uygun fiyatlar.',
        introHeading: 'March için bisikletler — Karaarslan Bike',
        introText: 'March (Hugstetten, Neuershausen, Holzhausen) [SEHIR]\'un batısında yer alıyor. Karaarslan Bike sadece 15 dakikada ulaşılabilir ve bölgenin en büyük bisiklet seçimini sunuyor — garantili 100\'den fazla yeni ve ikinci el bisiklet.',
        whyHeading: 'Neden bize gelmelisiniz?',
        whyItems: [
          'Sadece 10 km / 15 dakika arabayla',
          'Stokta 100\'den fazla bisiklet',
          'Garantili kontrol edilmiş ikinci el bisikletler',
          'Akü durumu belgelenmiş e-bisikletler',
          'Randevusuz test sürüşü',
        ],
        offerHeading: 'Ürün Yelpazemiz',
        offerItems: [
          'Günlük kullanım için şehir bisikletleri',
          'March – [SEHIR] güzergahı için e-bisikletler',
          'Breisgau\'da turlar için trekking bisikletleri',
          'Çocuk bisikletleri',
          'İkinci el bisikletler yaklaşık 80 €\'dan',
        ],
        ctaHeading: 'Bizi ziyaret edin!',
        ctaText: '[ADRES], [PLZ] [SEHIR]. Pzt/Sal/Per 11–18, Cum 11–13 + 15–18, Cmt 11:30–17. WhatsApp: [TELEFON].',
        directions: 'March\'dan Hugstetten/Umkirch üzerinden doğrudan [SEHIR]-Haslach\'a. Sadece 15 dakika.',
      },
    },
  },
];


